### ISSUE TITLE
How will posts be stored?

### ISSUE THREAD

**Issue by andybrwr** [inkron/old#11]
I know the answer is probably obvious and i'm just stupid but i still don't know

**Comment by znthlabs** [comment]
server

**Comment by andybrwr** [comment]
i mean since there's no php
or sql

**Comment by benajaero** [comment]
Database

**Comment by CatsAreFluffy** [comment]
Database? Like large text files?

**Comment by encloinc** [comment]
Im used to json

**Comment by CatsAreFluffy** [comment]
So...NoSQL?

**Comment by encloinc** [comment]
no no, sql is probably better. XD
