### ISSUE TITLE
Notepad++

### ISSUE THREAD

**Issue by pen-and-paper** [inkron/old#3]
Maybe we should use Notepad++ to write some of our code, it has a lot of good features and allows you to test-run code on the Web

**Comment by encloinc** [comment]
Have you ever used brackets? I recommend checking it out! Its really up to everyone's personal preferences on what they decide to use :)

**Comment by pen-and-paper** [comment]
Okay, I'll have a look :)

**Comment by benajaero** [comment]
It doesn't matter what you use...

**Comment by pen-and-paper** [comment]
I know, I just downloaded Brackets and find it pretty cool too, I just wanted to suggest Notepad++.

**Comment by benajaero** [comment]
Text editors are not important. As long as you can type code with them then it is good

**Comment by pen-and-paper** [comment]
True :)
